// Generated by Bisonc++ V5.02.00 on Sun, 10 Nov 2019 23:33:56 +0100

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION__ = 10
    };

// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {293, 1}, // 1: start ->  program
     {294, 7}, // 2: program (PROGRAM) ->  PROGRAM AZONOSITO VALTOZOK declarations UTASITASOK mainpart PROGRAM_VEGE
     {294, 5}, // 3: program (PROGRAM) ->  PROGRAM AZONOSITO UTASITASOK mainpart PROGRAM_VEGE
     {295, 1}, // 4: declarations ->  declaration
     {295, 2}, // 5: declarations ->  declarations declaration
     {297, 2}, // 6: declaration (AZONOSITO) ->  type AZONOSITO
     {298, 1}, // 7: type (EGESZ) ->  EGESZ
     {298, 1}, // 8: type (LOGIKAI) ->  LOGIKAI
     {296, 1}, // 9: mainpart ->  utasitas
     {296, 2}, // 10: mainpart ->  utasitas mainpart
     {299, 1}, // 11: utasitas (SKIP) ->  SKIP
     {299, 1}, // 12: utasitas ->  assignment
     {299, 1}, // 13: utasitas ->  be
     {299, 1}, // 14: utasitas ->  ki
     {299, 1}, // 15: utasitas ->  elagazas
     {299, 1}, // 16: utasitas ->  ciklus
     {300, 3}, // 17: assignment (AZONOSITO) ->  AZONOSITO SETTER kifejezes
     {301, 2}, // 18: be (BE) ->  BE AZONOSITO
     {302, 2}, // 19: ki (KI) ->  KI kifejezes
     {303, 5}, // 20: elagazas (HA) ->  HA kifejezes AKKOR mainpart HA_VEGE
     {303, 7}, // 21: elagazas (HA) ->  HA kifejezes AKKOR mainpart KULONBEN mainpart HA_VEGE
     {304, 5}, // 22: ciklus (CIKLUS) ->  CIKLUS AMIG kifejezes mainpart CIKLUS_VEGE
     {305, 3}, // 23: kifejezes (EQ) ->  kifejezes EQ kifejezes
     {305, 3}, // 24: kifejezes (GT) ->  kifejezes GT kifejezes
     {305, 3}, // 25: kifejezes (GTOREQ) ->  kifejezes GTOREQ kifejezes
     {305, 3}, // 26: kifejezes (LT) ->  kifejezes LT kifejezes
     {305, 3}, // 27: kifejezes (LTOREQ) ->  kifejezes LTOREQ kifejezes
     {305, 3}, // 28: kifejezes (STAR) ->  kifejezes STAR kifejezes
     {305, 3}, // 29: kifejezes (DIV) ->  kifejezes DIV kifejezes
     {305, 3}, // 30: kifejezes (MOD) ->  kifejezes MOD kifejezes
     {305, 3}, // 31: kifejezes (ES) ->  kifejezes ES kifejezes
     {305, 3}, // 32: kifejezes (VAGY) ->  kifejezes VAGY kifejezes
     {305, 3}, // 33: kifejezes (OPEN) ->  OPEN kifejezes CLOSE
     {305, 3}, // 34: kifejezes (PLUS) ->  kifejezes PLUS kifejezes
     {305, 3}, // 35: kifejezes (MINUS) ->  kifejezes MINUS kifejezes
     {305, 1}, // 36: kifejezes (IGAZ) ->  IGAZ
     {305, 1}, // 37: kifejezes (HAMIS) ->  HAMIS
     {305, 1}, // 38: kifejezes (AZONOSITO) ->  AZONOSITO
     {305, 2}, // 39: kifejezes (NEM) ->  NEM kifejezes
     {305, 1}, // 40: kifejezes (NUMBER) ->  NUMBER
     {306, 1}, // 41: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 4} },           
    { {       293}, { 1} }, // start  
    { {       294}, { 2} }, // program
    { {       259}, { 3} }, // PROGRAM
    { {         0}, { 0} },           
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, { 2} },             
    { {       258}, { 4} }, // AZONOSITO
    { {         0}, { 0} },             
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, { 3} },              
    { {       261}, { 5} }, // VALTOZOK  
    { {       262}, { 6} }, // UTASITASOK
    { {         0}, { 0} },              
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       295}, {  7} }, // declarations
    { {       297}, {  8} }, // declaration 
    { {       298}, {  9} }, // type        
    { {       263}, { 10} }, // EGESZ       
    { {       264}, { 11} }, // LOGIKAI     
    { {         0}, {  0} },                
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       296}, { 12} }, // mainpart  
    { {       299}, { 13} }, // utasitas  
    { {       267}, { 14} }, // SKIP      
    { {       300}, { 15} }, // assignment
    { {       301}, { 16} }, // be        
    { {       302}, { 17} }, // ki        
    { {       303}, { 18} }, // elagazas  
    { {       304}, { 19} }, // ciklus    
    { {       258}, { 20} }, // AZONOSITO 
    { {       276}, { 21} }, // BE        
    { {       275}, { 22} }, // KI        
    { {       268}, { 23} }, // HA        
    { {       272}, { 24} }, // CIKLUS    
    { {         0}, {  0} },              
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  6} },               
    { {       262}, { 25} }, // UTASITASOK 
    { {       297}, { 26} }, // declaration
    { {       298}, {  9} }, // type       
    { {       263}, { 10} }, // EGESZ      
    { {       264}, { 11} }, // LOGIKAI    
    { {         0}, {  0} },               
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       258}, { 27} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_10[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_11[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       260}, { 28} }, // PROGRAM_VEGE
    { {         0}, {  0} },                
};

SR__ s_13[] =
{
    { { REQ_DEF}, { 14} },              
    { {     296}, { 29} }, // mainpart  
    { {     299}, { 13} }, // utasitas  
    { {     267}, { 14} }, // SKIP      
    { {     300}, { 15} }, // assignment
    { {     301}, { 16} }, // be        
    { {     302}, { 17} }, // ki        
    { {     303}, { 18} }, // elagazas  
    { {     304}, { 19} }, // ciklus    
    { {     258}, { 20} }, // AZONOSITO 
    { {     276}, { 21} }, // BE        
    { {     275}, { 22} }, // KI        
    { {     268}, { 23} }, // HA        
    { {     272}, { 24} }, // CIKLUS    
    { {       0}, { -9} },              
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       292}, { 30} }, // SETTER
    { {         0}, {  0} },          
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       258}, { 31} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 32} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 39} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       273}, { 40} }, // AMIG
    { {         0}, {  0} },        
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       296}, { 41} }, // mainpart  
    { {       299}, { 13} }, // utasitas  
    { {       267}, { 14} }, // SKIP      
    { {       300}, { 15} }, // assignment
    { {       301}, { 16} }, // be        
    { {       302}, { 17} }, // ki        
    { {       303}, { 18} }, // elagazas  
    { {       304}, { 19} }, // ciklus    
    { {       258}, { 20} }, // AZONOSITO 
    { {       276}, { 21} }, // BE        
    { {       275}, { 22} }, // KI        
    { {       268}, { 23} }, // HA        
    { {       272}, { 24} }, // CIKLUS    
    { {         0}, {  0} },              
};

SR__ s_26[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_27[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_28[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_29[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 42} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_32[] =
{
    { { REQ_DEF}, {  13} },          
    { {     285}, {  43} }, // EQ    
    { {     286}, {  44} }, // GT    
    { {     287}, {  45} }, // GTOREQ
    { {     288}, {  46} }, // LT    
    { {     289}, {  47} }, // LTOREQ
    { {     280}, {  48} }, // STAR  
    { {     281}, {  49} }, // DIV   
    { {     282}, {  50} }, // MOD   
    { {     283}, {  51} }, // ES    
    { {     284}, {  52} }, // VAGY  
    { {     290}, {  53} }, // PLUS  
    { {     291}, {  54} }, // MINUS 
    { {       0}, { -19} },          
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 55} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 56} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       269}, { 57} }, // AKKOR 
    { {       285}, { 43} }, // EQ    
    { {       286}, { 44} }, // GT    
    { {       287}, { 45} }, // GTOREQ
    { {       288}, { 46} }, // LT    
    { {       289}, { 47} }, // LTOREQ
    { {       280}, { 48} }, // STAR  
    { {       281}, { 49} }, // DIV   
    { {       282}, { 50} }, // MOD   
    { {       283}, { 51} }, // ES    
    { {       284}, { 52} }, // VAGY  
    { {       290}, { 53} }, // PLUS  
    { {       291}, { 54} }, // MINUS 
    { {         0}, {  0} },          
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 58} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       260}, { 59} }, // PROGRAM_VEGE
    { {         0}, {  0} },                
};

SR__ s_42[] =
{
    { { REQ_DEF}, {  13} },          
    { {     285}, {  43} }, // EQ    
    { {     286}, {  44} }, // GT    
    { {     287}, {  45} }, // GTOREQ
    { {     288}, {  46} }, // LT    
    { {     289}, {  47} }, // LTOREQ
    { {     280}, {  48} }, // STAR  
    { {     281}, {  49} }, // DIV   
    { {     282}, {  50} }, // MOD   
    { {     283}, {  51} }, // ES    
    { {     284}, {  52} }, // VAGY  
    { {     290}, {  53} }, // PLUS  
    { {     291}, {  54} }, // MINUS 
    { {       0}, { -17} },          
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 60} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 61} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 62} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 63} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 64} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 65} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 66} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 67} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 68} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 69} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 70} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       305}, { 71} }, // kifejezes
    { {       277}, { 33} }, // OPEN     
    { {       265}, { 34} }, // IGAZ     
    { {       266}, { 35} }, // HAMIS    
    { {       258}, { 36} }, // AZONOSITO
    { {       279}, { 37} }, // NEM      
    { {       257}, { 38} }, // NUMBER   
    { {         0}, {  0} },             
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       278}, { 72} }, // CLOSE 
    { {       285}, { 43} }, // EQ    
    { {       286}, { 44} }, // GT    
    { {       287}, { 45} }, // GTOREQ
    { {       288}, { 46} }, // LT    
    { {       289}, { 47} }, // LTOREQ
    { {       280}, { 48} }, // STAR  
    { {       281}, { 49} }, // DIV   
    { {       282}, { 50} }, // MOD   
    { {       283}, { 51} }, // ES    
    { {       284}, { 52} }, // VAGY  
    { {       290}, { 53} }, // PLUS  
    { {       291}, { 54} }, // MINUS 
    { {         0}, {  0} },          
};

SR__ s_56[] =
{
    { { REQ_DEF}, {  13} },          
    { {     285}, {  43} }, // EQ    
    { {     286}, {  44} }, // GT    
    { {     287}, {  45} }, // GTOREQ
    { {     288}, {  46} }, // LT    
    { {     289}, {  47} }, // LTOREQ
    { {     280}, {  48} }, // STAR  
    { {     281}, {  49} }, // DIV   
    { {     282}, {  50} }, // MOD   
    { {     283}, {  51} }, // ES    
    { {     284}, {  52} }, // VAGY  
    { {     290}, {  53} }, // PLUS  
    { {     291}, {  54} }, // MINUS 
    { {       0}, { -39} },          
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       296}, { 73} }, // mainpart  
    { {       299}, { 13} }, // utasitas  
    { {       267}, { 14} }, // SKIP      
    { {       300}, { 15} }, // assignment
    { {       301}, { 16} }, // be        
    { {       302}, { 17} }, // ki        
    { {       303}, { 18} }, // elagazas  
    { {       304}, { 19} }, // ciklus    
    { {       258}, { 20} }, // AZONOSITO 
    { {       276}, { 21} }, // BE        
    { {       275}, { 22} }, // KI        
    { {       268}, { 23} }, // HA        
    { {       272}, { 24} }, // CIKLUS    
    { {         0}, {  0} },              
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, { 26} },              
    { {       296}, { 74} }, // mainpart  
    { {       285}, { 43} }, // EQ        
    { {       286}, { 44} }, // GT        
    { {       287}, { 45} }, // GTOREQ    
    { {       288}, { 46} }, // LT        
    { {       289}, { 47} }, // LTOREQ    
    { {       280}, { 48} }, // STAR      
    { {       281}, { 49} }, // DIV       
    { {       282}, { 50} }, // MOD       
    { {       283}, { 51} }, // ES        
    { {       284}, { 52} }, // VAGY      
    { {       290}, { 53} }, // PLUS      
    { {       291}, { 54} }, // MINUS     
    { {       299}, { 13} }, // utasitas  
    { {       267}, { 14} }, // SKIP      
    { {       300}, { 15} }, // assignment
    { {       301}, { 16} }, // be        
    { {       302}, { 17} }, // ki        
    { {       303}, { 18} }, // elagazas  
    { {       304}, { 19} }, // ciklus    
    { {       258}, { 20} }, // AZONOSITO 
    { {       276}, { 21} }, // BE        
    { {       275}, { 22} }, // KI        
    { {       268}, { 23} }, // HA        
    { {       272}, { 24} }, // CIKLUS    
    { {         0}, {  0} },              
};

SR__ s_59[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_60[] =
{
    { { REQ_DEF}, {   7} },          
    { {     286}, {  44} }, // GT    
    { {     287}, {  45} }, // GTOREQ
    { {     288}, {  46} }, // LT    
    { {     289}, {  47} }, // LTOREQ
    { {     290}, {  53} }, // PLUS  
    { {     291}, {  54} }, // MINUS 
    { {       0}, { -23} },          
};

SR__ s_61[] =
{
    { { REQ_DEF}, {   6} },          
    { {     287}, {  45} }, // GTOREQ
    { {     288}, {  46} }, // LT    
    { {     289}, {  47} }, // LTOREQ
    { {     290}, {  53} }, // PLUS  
    { {     291}, {  54} }, // MINUS 
    { {       0}, { -24} },          
};

SR__ s_62[] =
{
    { { REQ_DEF}, {   5} },          
    { {     288}, {  46} }, // LT    
    { {     289}, {  47} }, // LTOREQ
    { {     290}, {  53} }, // PLUS  
    { {     291}, {  54} }, // MINUS 
    { {       0}, { -25} },          
};

SR__ s_63[] =
{
    { { REQ_DEF}, {   4} },          
    { {     289}, {  47} }, // LTOREQ
    { {     290}, {  53} }, // PLUS  
    { {     291}, {  54} }, // MINUS 
    { {       0}, { -26} },          
};

SR__ s_64[] =
{
    { { REQ_DEF}, {   3} },         
    { {     290}, {  53} }, // PLUS 
    { {     291}, {  54} }, // MINUS
    { {       0}, { -27} },         
};

SR__ s_65[] =
{
    { { REQ_DEF}, {  12} },          
    { {     285}, {  43} }, // EQ    
    { {     286}, {  44} }, // GT    
    { {     287}, {  45} }, // GTOREQ
    { {     288}, {  46} }, // LT    
    { {     289}, {  47} }, // LTOREQ
    { {     281}, {  49} }, // DIV   
    { {     282}, {  50} }, // MOD   
    { {     283}, {  51} }, // ES    
    { {     284}, {  52} }, // VAGY  
    { {     290}, {  53} }, // PLUS  
    { {     291}, {  54} }, // MINUS 
    { {       0}, { -28} },          
};

SR__ s_66[] =
{
    { { REQ_DEF}, {  11} },          
    { {     285}, {  43} }, // EQ    
    { {     286}, {  44} }, // GT    
    { {     287}, {  45} }, // GTOREQ
    { {     288}, {  46} }, // LT    
    { {     289}, {  47} }, // LTOREQ
    { {     282}, {  50} }, // MOD   
    { {     283}, {  51} }, // ES    
    { {     284}, {  52} }, // VAGY  
    { {     290}, {  53} }, // PLUS  
    { {     291}, {  54} }, // MINUS 
    { {       0}, { -29} },          
};

SR__ s_67[] =
{
    { { REQ_DEF}, {  10} },          
    { {     285}, {  43} }, // EQ    
    { {     286}, {  44} }, // GT    
    { {     287}, {  45} }, // GTOREQ
    { {     288}, {  46} }, // LT    
    { {     289}, {  47} }, // LTOREQ
    { {     283}, {  51} }, // ES    
    { {     284}, {  52} }, // VAGY  
    { {     290}, {  53} }, // PLUS  
    { {     291}, {  54} }, // MINUS 
    { {       0}, { -30} },          
};

SR__ s_68[] =
{
    { { REQ_DEF}, {   9} },          
    { {     285}, {  43} }, // EQ    
    { {     286}, {  44} }, // GT    
    { {     287}, {  45} }, // GTOREQ
    { {     288}, {  46} }, // LT    
    { {     289}, {  47} }, // LTOREQ
    { {     284}, {  52} }, // VAGY  
    { {     290}, {  53} }, // PLUS  
    { {     291}, {  54} }, // MINUS 
    { {       0}, { -31} },          
};

SR__ s_69[] =
{
    { { REQ_DEF}, {   8} },          
    { {     285}, {  43} }, // EQ    
    { {     286}, {  44} }, // GT    
    { {     287}, {  45} }, // GTOREQ
    { {     288}, {  46} }, // LT    
    { {     289}, {  47} }, // LTOREQ
    { {     290}, {  53} }, // PLUS  
    { {     291}, {  54} }, // MINUS 
    { {       0}, { -32} },          
};

SR__ s_70[] =
{
    { { REQ_DEF}, {   2} },         
    { {     291}, {  54} }, // MINUS
    { {       0}, { -34} },         
};

SR__ s_71[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, {  3} },            
    { {       271}, { 75} }, // HA_VEGE 
    { {       270}, { 76} }, // KULONBEN
    { {         0}, {  0} },            
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       274}, { 77} }, // CIKLUS_VEGE
    { {         0}, {  0} },               
};

SR__ s_75[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       296}, { 78} }, // mainpart  
    { {       299}, { 13} }, // utasitas  
    { {       267}, { 14} }, // SKIP      
    { {       300}, { 15} }, // assignment
    { {       301}, { 16} }, // be        
    { {       302}, { 17} }, // ki        
    { {       303}, { 18} }, // elagazas  
    { {       304}, { 19} }, // ciklus    
    { {       258}, { 20} }, // AZONOSITO 
    { {       276}, { 21} }, // BE        
    { {       275}, { 22} }, // KI        
    { {       268}, { 23} }, // HA        
    { {       272}, { 24} }, // CIKLUS    
    { {         0}, {  0} },              
};

SR__ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  2} },           
    { {       271}, { 79} }, // HA_VEGE
    { {         0}, {  0} },           
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
};

} // anonymous namespace ends




// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ParserBase::setDebug(bool mode)
{
    d_actionCases__ = false;
    d_debug__ = mode;
}

void ParserBase::setDebug(DebugMode__ mode)
{
    d_actionCases__ = mode & ACTIONCASES;
    d_debug__ =       mode & ON;
}

void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    size_t currentSize = d_stateStack__.size();
    if (static_cast<size_t>(d_stackIdx__ + 1) == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION__;
        d_stateStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
        if (d_valueStack__.capacity() >= newSize)
            d_valueStack__.resize(newSize);
        else
        {
            std::vector<STYPE__> enlarged(newSize);
            for (size_t idx = 0; idx != currentSize; ++idx)
                enlarged[idx] = std::move(d_valueStack__[idx]);
            d_valueStack__.swap(enlarged);
        }
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = std::move(d_val__);
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = std::move(d_nextVal__);
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = std::move(d_val__);
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 47 "calculate.y"
        {
         std::cout << "start -> program" << std::endl;
         }
        break;

        case 2:
#line 54 "calculate.y"
        {
         std::cout << "program -> PROGRAM AZONOSITO VALTOZOK: declarations UTASITASOK: mainpart PROGRAM_VEGE" << std::endl;
         }
        break;

        case 3:
#line 59 "calculate.y"
        {
         std::cout << "program -> PROGRAM AZONOSITO UTASITASOK: mainpart PROGRAM_VEGE" << std::endl;
         }
        break;

        case 4:
#line 67 "calculate.y"
        {
         std::cout << "declarations -> declaration" << std::endl;
         }
        break;

        case 5:
#line 72 "calculate.y"
        {
         std::cout << "declarations -> declarations declaration" << std::endl;
         }
        break;

        case 6:
#line 80 "calculate.y"
        {
         std::cout << "declaration -> type AZONOSITO" << std::endl;
         }
        break;

        case 7:
#line 88 "calculate.y"
        {
         std::cout << "type -> EGESZ" << std::endl;
         }
        break;

        case 8:
#line 93 "calculate.y"
        {
         std::cout << "type -> LOGIKAI" << std::endl;
         }
        break;

        case 9:
#line 101 "calculate.y"
        {
         std::cout << "mainpart -> utasitas" << std::endl;
         }
        break;

        case 10:
#line 106 "calculate.y"
        {
         std::cout << "mainpart -> utasitas mainpart" << std::endl;
         }
        break;

        case 11:
#line 113 "calculate.y"
        {
         std::cout << "utasitas -> SKIP" << std::endl;
         }
        break;

        case 12:
#line 118 "calculate.y"
        {
         std::cout << "utasitas -> assignment" << std::endl;
         }
        break;

        case 13:
#line 123 "calculate.y"
        {
         std::cout << "utasitas -> be" << std::endl;
         }
        break;

        case 14:
#line 128 "calculate.y"
        {
         std::cout << "utasitas -> ki" << std::endl;
         }
        break;

        case 15:
#line 133 "calculate.y"
        {
         std::cout << "utasitas -> elagazas" << std::endl;
         }
        break;

        case 16:
#line 138 "calculate.y"
        {
         std::cout << "utasitas -> ciklus" << std::endl;
         }
        break;

        case 17:
#line 145 "calculate.y"
        {
         std::cout << "assignment -> AZONOSITO SETTER kifejezes" << std::endl; 
         }
        break;

        case 18:
#line 152 "calculate.y"
        {
         std::cout << "be -> BE AZONOSITO" << std::endl; 
         }
        break;

        case 19:
#line 159 "calculate.y"
        {
         std::cout << "ki -> KI kifejezes" << std::endl; 
         }
        break;

        case 20:
#line 167 "calculate.y"
        {
         std::cout << "elagazas -> HA kifejezes AKKOR mainpart HA_VEGE" << std::endl; 
         }
        break;

        case 21:
#line 172 "calculate.y"
        {
         std::cout << "elagazas -> HA kifejezes AKKOR mainpart KULONBEN mainpart HA_VEGE" << std::endl; 
         }
        break;

        case 22:
#line 179 "calculate.y"
        {
         std::cout << "ciklus -> CIKLUS AMIG kifejezes mainpart CIKLUS_VEGE" << std::endl; 
         }
        break;

        case 23:
#line 187 "calculate.y"
        {
         std::cout << "kifejezes -> EQ" << std::endl;
         }
        break;

        case 24:
#line 192 "calculate.y"
        {
         std::cout << "kifejezes -> GT" << std::endl;
         }
        break;

        case 25:
#line 197 "calculate.y"
        {
         std::cout << "kifejezes -> GTOREQ" << std::endl;
         }
        break;

        case 26:
#line 202 "calculate.y"
        {
         std::cout << "kifejezes -> LT" << std::endl;
         }
        break;

        case 27:
#line 207 "calculate.y"
        {
         std::cout << "kifejezes -> LTOREQ" << std::endl;
         }
        break;

        case 28:
#line 212 "calculate.y"
        {
         std::cout << "kifejezes -> STAR " << std::endl;
         }
        break;

        case 29:
#line 217 "calculate.y"
        {
         std::cout << "kifejezes -> DIV " << std::endl;
         }
        break;

        case 30:
#line 222 "calculate.y"
        {
         std::cout << "kifejezes -> MOD " << std::endl;
         }
        break;

        case 31:
#line 227 "calculate.y"
        {
         std::cout << "kifejezes -> kifejezes ES kifejezes" << std::endl;
         }
        break;

        case 32:
#line 232 "calculate.y"
        {
         std::cout << "kifejezes -> kifejezes VAGY kifejezes" << std::endl;
         }
        break;

        case 33:
#line 237 "calculate.y"
        {
         std::cout << "kifejezes -> OPEN kifejezes CLOSE" << std::endl;
         }
        break;

        case 34:
#line 242 "calculate.y"
        {
         std::cout << "kifejezes -> kifejezes PLUS kifejezes" << std::endl;
         }
        break;

        case 35:
#line 247 "calculate.y"
        {
         std::cout << "kifejezes -> kifejezes MINUS kifejezes" << std::endl;
         }
        break;

        case 36:
#line 252 "calculate.y"
        {
         std::cout << "kifejezes -> IGAZ" << std::endl;
         }
        break;

        case 37:
#line 257 "calculate.y"
        {
         std::cout << "kifejezes -> HAMIS" << std::endl;
         }
        break;

        case 38:
#line 262 "calculate.y"
        {
         std::cout << "kifejezes -> AZONOSITO" << std::endl;
         }
        break;

        case 39:
#line 267 "calculate.y"
        {
         std::cout << "kifejezes -> NEM kifejezes" << std::endl;
         }
        break;

        case 40:
#line 272 "calculate.y"
        {
         std::cout << "kifejezes -> NUMBER" << std::endl;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



