// Generated by Bisonc++ V4.01.00 on Tue, 18 Nov 2014 09:41:34 +0100

#ifndef Parser_h_included
#define Parser_h_included

// $insert baseclass
#include "Parserbase.h"
#include <FlexLexer.h>
#include <iostream>
#include <cstdlib>
#include <map>
#include "semantics.h"

#undef Parser
class Parser: public ParserBase
{
        
    public:
        Parser(std::istream& inFile) : lexer( &inFile, &std::cerr ) {}
        int parse();

    private:
        yyFlexLexer lexer;
        void error(char const *msg);    // called on (syntax) errors
        int lex();                      // returns the next token from the
                                        // lexical scanner. 
        void print();                   // use, e.g., d_token, d_loc

    // support functions for parse():
        void executeAction(int ruleNr);
        void errorRecovery();
        int lookup(bool recovery);
        void nextToken();
        void print__();
        
        std::map<std::string,valtozo_leiro> szimb_tabla;
        static int sorszam;
};


#endif
